services:
  whoogle-search:
    image: benbusby/whoogle-search:latest
    container_name: whoogle
    logging:
      driver: loki
      options:
        loki-url: "https://loki.hughboi.cc/loki/api/v1/push"
        loki-retries: 2
        loki-max-backoff: 800ms
        loki-timeout: 1s
        keep-file: "true"
        mode: "non-blocking"
    restart: unless-stopped
    pids_limit: 50
    mem_limit: 256mb
    memswap_limit: 256mb
    user: whoogle
    security_opt:
      - no-new-privileges
    cap_drop:
      - ALL
    tmpfs:
      - /config/:size=10M,uid=927,gid=927,mode=1700
      - /var/lib/tor/:size=15M,uid=927,gid=927,mode=1700
      - /run/tor/:size=1M,uid=927,gid=927,mode=1700
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.whoogle.entrypoints=http
      - traefik.http.routers.whoogle.rule=Host(`whoogle.hughboi.cc`)
      - traefik.http.middlewares.whoogle-https-redirect.redirectscheme.scheme=https
      - traefik.http.routers.whoogle.middlewares=whoogle-https-redirect
      - traefik.http.routers.whoogle-secure.entrypoints=https
      - traefik.http.routers.whoogle-secure.rule=Host(`whoogle.hughboi.cc`)
      - traefik.http.routers.whoogle-secure.tls=true
      - traefik.http.routers.whoogle-secure.tls.certresolver=cloudflare
      - traefik.http.services.whoogle.loadbalancer.server.port=5000
networks:
  proxy:
    external: true
